[alias]
android-sysprop = "run -p cargo-android-sysprop --bin cargo-android-sysprop --"
push-resetprop = "run -p cargo-android-sysprop --bin resetprop-tester -- --target aarch64-linux-android"
test-resetprop = "run -p cargo-android-sysprop --bin resetprop-tester -- --target aarch64-linux-android --run-test"